# Generated by Django 4.2.5 on 2023-09-06 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("test_app", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="User",
            new_name="Data",
        ),
    ]
